#!/usr/bin/env python3
import re

Nobody_text = '''Nobody by Shel Silverstein
Nobody loves me,
Nobody cares,
Nobody picks me peaches and pears.
Nobody offers me candy and Cokes,
Nobody listens and laughs at me jokes.
Nobody helps when I get in a fight,
Nobody does all my homework at night.
Nobody misses me,
Nobody cries,
Nobody thinks I'm a wonderful guy.
So if you ask me who's my best friend, in a whiz,
I'll stand up and tell you that Nobody is.
But yesterday night I got quite a scare,
I woke up and Nobody just wasn't there.
I called out and reached out for Nobody's hand,
In the darkness where Nobody usually stands.
Then I poked through the house, in each cranny and nook,
But I found somebody each place that I looked.
I searched till I'm tired, and now with the dawn,
There's no doubt about it-
Nobody's gone!'''

found=re.findall(r'Nobody',Nobody_text)
print(found)

found=re.search(r'Nobody',Nobody_text)
print(found)



for match in re.finditer(r'Nobody',Nobody_text):
  print('position:', found)

# change the word Nobody to Brownie
Nobody_text.replace('Nobody','Brownie')
print(Nobody_text)
Brownie_text = Nobody_text.replace('Nobody','Brownie')
print(Brownie_text)

#save with the new name 
fo = open('Brownie.txt' , 'w')
fo.write(Brownie_text)
fo.close()


FASTA_seq = open('Python_07.fasta' , 'r')
for line in FASTA_seq:
  line = line.rstrip()
  print(line)

FASTA_header=re.findall(r'>\w+\s?.*' , FASTA_seq)
print(FASTA_header)
  
