#!/usr/bin/env python3

fav_dict = {'book':'war and peace','song':'Love','tree':'Cedar'}
print(fav_dict['book'])
fav_thing = 'book'
print(fav_dict[fav_thing])

print(fav_dict['tree'])
fav_dict['organism'] = 'pinguin'
print(fav_dict)
fav_thing = 'organism'
print(fav_dict[fav_thing])

# Use a for loop to print out each key and value of the dictionary.

for fav_thing in fav_dict:
  value=fav_dict[fav_thing]
  print(f'Key: {fav_thing}, Value: {value}')

#Take a value from the command line for fav_thing and print the value of that item from the dictionary.
