#!/usr/bin/env python3
import sys
count = int( sys.argv[1])
if count > 0:
  message = "Yep, it more then 0,positive"
  print (count, message)
  if count < 50: 
    message = "less then 50"
    print (count, message)
    if count %2 ==0:
      message = "it is an even number that is smaller than 50"
      print (count, message)
    else:
      message = "odd number"
      print (count, message)
  if count > 50:
    message = " more then 50"
    print (count, message)
    if count %3 ==0:
      message = "it is larger than 50 and divisible by 3"
      print (count, message) 
 
elif count < 0:
  message = "Yes, its less then 0, negative"
  print (count, message)

elif count == 0:
  message = "Its zero"
  print (count, message)

else:
  message = "must be 50"
  print (count, message) 
