#!/usr/bin/env python3

import sys

this data = {}

B_file = open('ss_rand5-200_v_qfo_BL50.txt','r')

print(B_file)

for line in B_file:
    line = line.rstrip()
    [qseqid, sseqid, percid, alen, mismat, gaps, q_start, q_end, s_start, s_end, evalue, bits] = line.split('\t')

    this_data = dict(zip(B_file, line.split('\t'))) 
    print(this_data)
   
    


